### PR TITLE
Chore/1.0.0

### PR DESCRIPTION
**Pull request by Baroshem**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by vejja** [comment]
@Baroshem We have 2 reported regressions, let me fix these first as they were introduced by me on rc5

**Comment by vejja** [comment]
It's ok now
PR #318 and PR #320 fix the regressions

**Comment by Baroshem** [comment]
@vejja 

Let me know if there is a 🟢 light from you :)

**Comment by vejja** [comment]
> @vejja
> 
> Let me know if there is a 🟢 light from you :)

@Baroshem
Sorry, let me get my head over the implications of #321 first.
It's an easy change and I want to be sure we don't break existing functionalities

**Comment by vejja** [comment]
> > @vejja
> > Let me know if there is a 🟢 light from you :)
> 
> @Baroshem Sorry, let me get my head over the implications of #321 first. It's an easy change and I want to be sure we don't break existing functionalities

#321 fixed by #322

**Comment by Baroshem** [comment]
@vejja 

Thanks for this additional research from you side and solving the edge case!

Let's merge this PR and test it next week. I think we can postpone the release to next week (for example wednesday) to see if there will be more bugfixes reported over the weekend.

**Comment by Baroshem** [comment]
@vejja 

I have tested all my paths and this seems to be working well. 

There is one small bug that I will open that we can fix for the 1.0.1 version which is about frame-ancestors in SSG does is ignored so we could programatically remove it from the meta tag. So it is some sort of a feature/bugfix.

Let me know if we have a 🟢 light from you and if so I will proceed with the release :)

**Comment by vejja** [comment]
> @vejja
> 
> I have tested all my paths and this seems to be working well.
> 
> There is one small bug that I will open that we can fix for the 1.0.1 version which is about frame-ancestors in SSG does is ignored so we could programatically remove it from the meta tag. So it is some sort of a feature/bugfix.
> 
> Let me know if we have a 🟢 light from you and if so I will proceed with the release :)

Yes, let’s release !!!
And more importantly : Congratulations 🎊🎈🍾🎉

**Comment by Baroshem** [comment]
Huge kudos to you @vejja 🚀

You are doing an amazing work making this module more secure than ever! So happy to have you as a maintainer and core part of the module 💚

**Pull request merged**
