### PR TITLE
Update nitro.ts

### PR DESCRIPTION
**Pull request by Maxp777**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey @Maxp777 

Could you explain why this change is needed?

**Comment by Maxp777** [comment]
like here https://nitro.unjs.io/guide/advanced/plugins

**Comment by Baroshem** [comment]
@Maxp777 

But it works the same as what it is there right now. Also, this is how other modules are registering nitro plugins -> https://github.com/nuxt-modules/html-validator/blob/main/src/runtime/nitro.ts

**Comment by Maxp777** [comment]
> @Maxp777
> 
> But it works the same as what it is there right now. Also, this is how other modules are registering nitro plugins -> https://github.com/nuxt-modules/html-validator/blob/main/src/runtime/nitro.ts

I don't understand why they added it then defineNitroPlugin

**Pull request closed without merging**
