### PR TITLE
Chore/1.1.0

### PR DESCRIPTION
**Pull request by Baroshem**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
@vejja @dargmuesli @huang-julien 

Sorry, I was a bit busy recently. Do you think that we could release the new version with these changes?

**Comment by dargmuesli** [comment]
I think everything around the `nuxt-security:headers` hook / runtime config in general is likely to change soon. Thus I'd recommend to document it as experimental (at least until https://github.com/Baroshem/nuxt-security/discussions/346 is resolved)!

**Comment by huang-julien** [comment]
@dargmuesli it's currently under the `runtimeHooks` option

**Comment by Baroshem** [comment]
Folks, I am proceeding with the release of the new version today :)

**Comment by Baroshem** [comment]
The version 1.1.0 was released!

Thank you so much for all the work!

**Pull request merged**
