### PR TITLE
feat(doc): introduce Nuxt Scripts as alternative to `useScript`

### PR DESCRIPTION
**Pull request by vejja**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

This PR is only a doc change on how to load 3rd-party scripts.
Instead of `useScript`, we recommend using the Nuxt Scripts module

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by vejja** [comment]
@harlan-zw I'm updating our docs to stop recommending importing `useScript` directly from 'unjs/unhead', and instead recommend using the Nuxt Scripts module. Would you agree with this change or is there something we should consider here ?

**Comment by harlan-zw** [comment]
Yes good to go, thanks for asking.

**Comment by Baroshem** [comment]
Thanks @harlan-zw !

@vejja would you like to merge the PR now? :)

**Comment by Baroshem** [comment]
Released in 2.0.0 :)

**Pull request merged**
