### PR TITLE
Chore/1.0.0 rc.1

### LINKED ISSUE #128: Remove console.logs after build
### Is your feature request related to a problem? Please describe.

https://github.com/nuxt/nuxt/issues/19702

### LINKED ISSUE #135: [Docs] Refactor docs to be easier

### LINKED ISSUE #167: CSRF tokens cause breakage on build using serverless environments due to incompatible exports of Node Crypto
### Version

nuxt-security: v0.13.1
nuxt: v3.6.0
nuxt-csrf: v1.2.0

### Reproduction Link

https://github.com/69u/NS-Serverless-Reproduction

### Steps to reproduce

1. Build the project using yarn build

### What is Expected?

1. App should return a heading that contains a generated CSRF token

### What is actually happening?

1. The app displays the CSRF token perfectly when in development
2. Upon building the app, Nuxt-CSRF cannot find some exports of crypto as they do not exist in serverless environments

### Possible Solution?

@zsilbi has created a fork of Nuxt-CSRF supporting serverless environments, potentially create a configuration for these serverless environments and use this forked version of the module instead: https://github.com/zsilbi/nuxt-csurf

### LINKED ISSUE #183: Bump packages to newer versions
### Describe the solution you'd like

remote: GitHub found 32 vulnerabilities on Baroshem/nuxt-security's default branch (14 high, 17 moderate, 1 low). To find out more, visit:
remote:      https://github.com/Baroshem/nuxt-security/security/dependabot

### LINKED ISSUE #190: Make `rateLimiter` optional
### Describe the solution you'd like

In several examples, rateLimiter is not suitable for production applications. I recommend to make it optional instead of enabling it by default.

### LINKED ISSUE #191: Remove legacy approach for middlewares in types and module.ts file

### LINKED ISSUE #192: Create faq section in docs from questions in Github issues

### LINKED ISSUE #194: Invalid permission policy parser
### Version

nuxt-security: 0.14.4
nuxt: 3.6.5

### Reproduction Link

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-zsju5u?file=nuxt.config.ts)

### Steps to reproduce

```js
// nuxt.config.ts / security.headers
security: {
  headers: {
    permissionsPolicy: {
      geolocation: ["self", '"https://api.website.com"'],
      midi: [],
      payment: [],
      camera: ["self", '"https://api.website.com"'],
      microphone: ["self", '"https://api.website.com"'],
      usb: [],
      magnetometer: [],
      "document-domain": [],
    },
  },
},
```

### What is Expected?

```
geolocation=(self "https://api.website.com"), midi=(), payment=(), camera=(self "https://api.website.com"), microphone=(self "https://api.website.com"), usb=(), magnetometer=(), document-domain=()
```

### What is actually happening?
```
camera=self "https://api.website.com", display-capture=(), fullscreen=(), geolocation=self "https://api.website.com", microphone=self "https://api.website.com"
```

### LINKED ISSUE #203: useCsrf() is undefined
Request header 
Csrf-Token: undefined

```
ssr: false,

security: {
enabled: true,
    csrf: { // optional
      https: false, // default true if in production
      cookieKey: '', // "__Host-csrf" if https is true otherwise just "csrf"
      cookie: { // CookieSerializeOptions from unjs/cookie-es
        path: '/',
        httpOnly: true,
        sameSite: 'strict'
      },
      methodsToProtect: ['POST', 'PUT', 'PATCH'], // the request methods we want CSRF protection for
      // excludedUrls: ['/nocsrf1', ['/nocsrf2/.*', 'i']], // any URLs we want to exclude from CSRF protection
      // encryptSecret: /** a 32 bits secret */, // random bytes by default
      encryptAlgorithm: 'aes-256-cbc'
    },
}
```

````
await useCsrfFetch('api/auth/signup', {
      body: payload,
      method: 'POST',
    });


const { csrf } = useCsrf(); // undefined

````

```
Cookie:
csrf=3c8a73c6-690c-48f2-92b4-3b100ef352ae;
```

### LINKED ISSUE #205: Move logic of Static plugins to the top of module.ts to decrease the amount of code for SSG apps

### LINKED ISSUE #214: fix: `upgrade-insecure-requests` cannot be turned off for static build
### Version

nuxt-security: 0.14.4
nuxt: 3.7.3

### Reproduction Link

https://stackblitz.com/edit/github-xdxcbc?file=nuxt.config.ts

### Steps to reproduce

run `nuxt generate`, then `npx serve .output/public` and inspect the content-security-policy header

### What is Expected?

As it's set to `false` in nuxt's configuration there should be no `upgrade-insecure-requests` policy

### What is actually happening?

There is a `upgrade-insecure-requests` policy.

### LINKED ISSUE #218: Content-Security-Policy: The page’s settings blocked the loading of a resource at inline
Recently I added Nuxt Security in a Project where i am fetching data from an API URL http://127.0.0.1:8000/api/blog/post/27
While displaying image it throws error
`Content-Security-Policy: The page’s settings blocked the loading of a resource at http://127.0.0.1:8000/api/blog/post_image/img12.jpg (“img-src”).`
Which i fixed using below settings
```
  security: {
    headers: {
      contentSecurityPolicy: {
        'img-src': ["'self'", 'data:', 'http://127.0.0.1:8000'],     // This line fixed it
      },
      strictTransportSecurity: 'max-age=0;'
    },
  },
```
and adding `crossorigin="anonymous"` in img tag ``
This fixed the issue but now i am implementing Nuxt Image Module and when i write `<NuxtImg crossorigin="anonymous" :src="postDetail.post_image" />`
It throws an error (only on Firefox doesn't throw error on chrome and edge)
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src-attr”).
Source: this.setAttribute('data-error', 1)
```
which i fixed using below settings
  ```
security: {
    headers: {
      contentSecurityPolicy: {
        'img-src': ["'self'", 'data:', 'http://127.0.0.1:8000'],
        'script-src-attr': ["'unsafe-inline'"],        // Added this
      },
      strictTransportSecurity: 'max-age=0;'
    },
  },
```
My concern is, it is considered a security risk, as it can open the door to XSS attacks. It's generally recommended to avoid using 'unsafe-inline' whenever possible.
Is there any other secure way to fix this error ?

### LINKED ISSUE #219: Add an include option for basicAuth
### Is your feature request related to a problem? Please describe.
Currently, the `basicAuth` option accept only `exclude` routes options but I need to protect one API route with basicAuth (for webhook purpose).

### Describe the solution you'd like
Add an `include` option for basicAuth to set the route I want to protect.

### Describe alternatives you've considered
Maybe access to basicAuth inside `routeRules` option can be a proper alternative ?

### LINKED ISSUE #229: Stripe blocked by 'Cross-Origin-Embedder-Policy'
After configuring @nuxt/security module, my Stripe requests are being blocked by the Cross-Origin-Embedder-Policy. While reading the documentation, I tried to configure it on a per-route basis as shown below:

```nuxt.config.ts
security: {
    headers: {
      // Default config!
      contentSecurityPolicy: {
        'base-uri': ["'self'"],
        'font-src': ["'self'", 'https:', 'data:'],
        'form-action': ["'self'"],
        'frame-ancestors': ["'self'"],
        'img-src': ["'self'", 'data:'],
        'object-src': ["'none'"],
        'script-src-attr': ["'none'"],
        'style-src': ["'self'", 'https:', "'unsafe-inline'"],
        'upgrade-insecure-requests': process.env.NODE_ENV !== 'development'
      },
      crossOriginResourcePolicy: 'cross-origin',
      crossOriginOpenerPolicy: 'unsafe-none',
      crossOriginEmbedderPolicy: 'require-corp'
    }
  },
  routeRules: {
    '/account': {
      headers: {
        'Cross-Origin-Embedder-Policy': 'unsafe-none'
      }
    }
  },
```

However, the policy only changes when I refresh the page. Is there any other configuration I should do within the module or Nuxt itself, or is this a limitation?

image

### PR DESCRIPTION
**Pull request by Baroshem**
Closes #205 [n4an](https://github.com/n4an)
Closes #203 
Closes #191 
Closes #190 
Closes #183 
Closes #167 [69u](https://github.com/69u)
Closes #135 
Closes #128 [pi0](https://github.com/pi0)
Closes #214 [dargmuesli](https://github.com/dargmuesli)
Closes #219 [Applelo](https://github.com/Applelo)
Closes #192 
Closes #217 [maxdzin](https://github.com/maxdzin)
Closes #218 [trijpstra-fourlights](https://github.com/trijpstra-fourlights)
Closes #198 [dargmuesli](https://github.com/dargmuesli)
Closes #215 [jekuer](https://github.com/jekuer)
Closes #229 [fabricioOak](https://github.com/fabricioOak)
Closes #194 [nekotoriy](https://github.com/nekotoriy)
Issues with inlined storage - [vejja](https://github.com/vejja)

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey @trijpstra-fourlights

I am experiencing some issues with the unit tests you have written for the module. Could you please take a look at them? :)

GitHub Action `ci` will tell you more details :)

**Comment by trijpstra-fourlights** [comment]
> Hey @trijpstra-fourlights
> 
> I am experiencing some issues with the unit tests you have written for the module. Could you please take a look at them? :)
> 
> GitHub Action `ci` will tell you more details :)

https://github.com/Baroshem/nuxt-security/pull/213#issue-1906992398

**Comment by chrisspiegl** [comment]
I'm very much looking forward to this release. Can't wait 👍.

**Comment by dargmuesli** [comment]
This PR already accumulated a few changes that I would like to try out in my projects! For me it's totally cool to have a rc2, rc3, ... and so on. Could this rc be released soon? :pray:

**Comment by Baroshem** [comment]
@dargmuesli 

Actually really really soon!

Stay tuned! 😉

**Comment by Baroshem** [comment]
🔥

**Pull request merged**
