### PR TITLE
docs: added trpc-nuxt configuration section

### PR DESCRIPTION
**Pull request by kouts**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation addition 

## Description

This PR adds a section for `trpc-nuxt`, specifically on how to make the `CSRF` functionality work.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by kouts** [comment]
Hey @Baroshem thanks for this wonderful Nuxt module.
I recently needed to enable the CSRF protection functionality to my `trpc-nuxt` enabled app and I couldn't find any related documentation. Hopefully this will help others looking for the same thing.

**Comment by Baroshem** [comment]
Hey @kouts 

Thanks for this PR! I can for sure see use cases for that. Kudos for documenting that.

One thing that I wanted to mention before merging. Could you please also add a note in this docs section about what would be the use case for having trpc with csrf (nuxt-security)? I understand clearly from the docs you written how to implement that but this docs section would benefit a lot from having a clear explanation why someone would want to use it for example:

`Using trpc with carf comes with a useful advantage X that will help you achieve Y`

Let me jnow what you think about it :)

**Comment by kouts** [comment]
Hey @Baroshem thanks, I've added a relevant section with [4333304](https://github.com/Baroshem/nuxt-security/pull/201/commits/4333304bc6d3650b711bab390d552bb1f01f4de6), feel free to make any changes.

**Comment by Baroshem** [comment]
@kouts 

Now it looks much better! Thank you! 

I will merge it and update the documentation :)

**Pull request merged**
