### PR TITLE
feat: support reading from websockets

### PR DESCRIPTION
**Pull request by GalacticHypernova**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This is a WIP PR to add support for reading messages from websockets, fixing #472 . It relies on the underlying socket in the connection and is therefore experimental. Due to the inability to test the module locally as stackblitz always regenerated the necessary file, I am adding this here to experiment with.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
Tests will arrive later

### CODE REVIEW

**Comment by GalacticHypernova** [comment]
@Baroshem can we introduce some dependencies for some of the tests? (like websockets) Or should the module stay dependency-free?

**Comment by Baroshem** [comment]
@GalacticHypernova 

Hey there! The best would be to remain deps free 🙂

**Comment by GalacticHypernova** [comment]
How would we test websockets in such case? Through nitro's built in websocket system?

**Comment by Baroshem** [comment]
Thanks for investigation @GalacticHypernova. Should we close this PR or remain as is?

**Comment by GalacticHypernova** [comment]
It depends. Would you like me to make a custom data reading method to not rely on h3's?

**Comment by Baroshem** [comment]
I dont think so. We are relying in H3 so I wouldnt test any other setup

**Comment by GalacticHypernova** [comment]
In that case we can close this, I forwarded the issue to h3 =)

**Pull request closed without merging**
