### PR TITLE
docs-#558: refactor docs new version

### LINKED ISSUE #570: The default behavior of `removeLoggers` is not correctly documented
### Version

nuxt-security: 2.1.4
nuxt: 3.14.1592

### Reproduction Link

Blank project without `removeLoggers` specified or set to `true`
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  security: {},
  // or 
  // security: { removeLoggers: true },
});
```

### Steps to reproduce

Configure the `nuxt.config.ts` like above and access to nuxt app in production mode.  
(In my case, i used `nuxt generate` to generate a static site)

### What is Expected?

Only the `log` and `debug` logger are removed as described in the document: 
> Fortunately, nuxt-security module removes both `log` and `debug` console outputs by default so your application is not leaking this information.
> ref: https://nuxt-security.vercel.app/documentation/utils/remove-console-loggers#:~:text=nuxt%2Dsecurity%20module%20removes%20both%20log%20and%20debug

### What is actually happening?

All the loggers (included `warn` and `error`) are removed.

### PR DESCRIPTION
**Pull request by Baroshem**
This PR rewrites documentation from Docus (pinceau) to Nuxt UI Pro with TailwindCSS to solve the recently discovered several issues -> https://github.com/Baroshem/nuxt-security/issues/557

@vejja I would appreciate your 👀 here as there are many changes and I could miss something (also some concepts have changed slightly like alerts -> callouts, headings, etc).

Closes #570

### CODE REVIEW

**Review by vejja — APPROVED** [review]
Impressive !

**Comment by Baroshem** [comment]
What is currently blocking me with it is the following error in Vercel that I am not sure what caused :( 

image

**Comment by vejja** [comment]
> What is currently blocking me with it is the following error in Vercel that I am not sure what caused :(
> 
> image

Can't really help unfortunately as the Nuxt UI Pro license keys prevent me from deploying on my side
Is there a way to test build without license keys ?

**Comment by Baroshem** [comment]
@vejja 

I have shared with you the key to Nuxt UI Pro in Discord.

Could you try to debug it? I have no idea what to do :(

**Comment by vejja** [comment]
> @vejja
> 
> I have shared with you the key to Nuxt UI Pro in Discord.
> 
> Could you try to debug it? I have no idea what to do :(

will have a look at it

**Pull request merged**
