### PR TITLE
Chore/2.1.0

### LINKED ISSUE #541: Nonce doesn't change per request in production build
Hi,

I've added a CSP but I'm having an issue with nonces not changing for a production deployment.

Running **npm run dev** the nonce changes per request.

image

Running **npm run build** , the nonce doesn't change. It's always this:

image

This happens in my local environment build and in production build which is Cloudflare Pages.

I tried a couple of versions both having the same result:
_nuxt-security: 2.0.0-rc.9
nuxt-security: v2.0.0
nuxt: 3.12.3_

The CSP I'm using is the same as listed on the FAQ page for Cloudflare config (https://nuxt-security.vercel.app/documentation/advanced/faq)

Is this a known issue and maybe I've missed a configuration?

### PR DESCRIPTION
**Pull request by Baroshem**
Fix devtools being blocked when strict mode is enabled

https://github.com/Baroshem/nuxt-security/commit/88dbb4c4f7d10e05a01336d6bf409e1434aaabd5 the existing documentation has been removed, so it should work the same in strict mode as in none-strict mode

ref: https://github.com/Baroshem/nuxt-security/issues/487

Closes https://github.com/Baroshem/nuxt-security/issues/526
Closes https://github.com/Baroshem/nuxt-security/issues/535
Closes https://github.com/Baroshem/nuxt-security/issues/533
Closes https://github.com/Baroshem/nuxt-security/issues/538
Possibly closes https://github.com/Baroshem/nuxt-security/issues/477
Closes #541 
Closes https://github.com/Baroshem/nuxt-security/issues/489

### CODE REVIEW

**Comment by Baroshem** [comment]
@vejja Do you think that we are ready to release this version? :)

**Review by vejja — APPROVED** [review]

**Comment by vejja** [comment]
Hey @Baroshem - I had to install the GitHub Actions script on main so that in can run on branches
But it works now!

**Comment by Baroshem** [comment]
Awesome, I will release it soon :)

**Review by vejja — APPROVED** [review]

**Review by vejja — APPROVED** [review]
Test:
Approving these changes for the sake of running the pr.pkg.new bot

**Pull request merged**
