### PR TITLE
feat: support using regular expressions as CORS origin

### PR DESCRIPTION
**Pull request by P4sca1**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Changes CORS options type to only allow serializable values. Add a new `useRegExp` property, that when set to true parses all origin values to a RegExp.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
Looks great to me, @vejja what are your thoughts on that? Could we make it for the 2.0.0 release? Or should we reschedule it to 2.1.0? :)

**Comment by P4sca1** [comment]
@Baroshem Are there any news? Would be great if this could be merged and a new RC release gets drafted.

**Comment by Baroshem** [comment]
@vejja looking for your feedback :)

**Comment by vejja** [comment]
LGTM, sorry for delay

**Pull request merged**
