### PR TITLE
fix(csrf): replace CSRF option `false` with `boolean`

### PR DESCRIPTION
**Pull request by Mohamed-Kaizen**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
image

**IDE**: webstorm

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey Buddy,

Thanks for creating a PR but I think that it is not correct. 

For CSRF, you should either set the `csrf` property in the config to an object (https://github.com/Morgbn/nuxt-csurf?tab=readme-ov-file#usage) or false to disable it if you dont need it. 

Same for other middlewares - Usually it is either about having them enabled with some configuration or disabled with `false`.

Only below ones can have true/false values:

```ts
  hidePoweredBy: boolean;
  enabled: boolean;
  nonce: boolean;
```

So the current behavior is correct and intentional.

I am glad for your contribution though so I would like to recommend you for the future to open an issue/question first. Then it will allow to avoid work that cannot be merged later on :)

**Comment by Mohamed-Kaizen** [comment]
> For CSRF, you should either set the csrf property in the config to an object (https://github.com/Morgbn/nuxt-csurf?tab=readme-ov-file#usage) or false to disable it if you dont need it.

The [documentation](https://nuxt-security.vercel.app/documentation/middleware/csrf)  says that you can enable CSRF by setting `security.csrf` to `true` in your Nuxt configuration.However, this does not work with TypeScript. I believe that either the TypeScript types or the documentation need to be updated to reflect this.

Additionally, I believe that having `security.csrf`  set to  `true`  would make it easier for users who want the recommended configuration, unless they need to customize it. The same is true for other middlewares.

>I am glad for your contribution though so I would like to recommend you for the future to open an issue/question first. Then it will allow to avoid work that cannot be merged later on :)

Yeah,  i will do that

**Comment by Baroshem** [comment]
Hey @Mohamed-Kaizen 

indeed you are correct. The docs says it correctly while the type here is not correct.

Instead of:

```ts
export interface ModuleOptions {
  csrf: CsrfOptions | false;
}
```

It should be:

```ts
export interface ModuleOptions {
  csrf: CsrfOptions | boolean;
}
```

Could you please correct just this line? Others are correct :)

**Comment by vejja** [comment]
@Baroshem Just fixed this one, can be merged

**Comment by Baroshem** [comment]
Awesome, thank you @vejja 

I will release it with the upcoming 1.0.0 next week as it is a really small bug fix ;)

**Review by Baroshem — APPROVED** [review]

**Pull request merged**
