### PR TITLE
feat(csp): support style nonce in development

### PR DESCRIPTION
**Pull request by dargmuesli**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Allows to use `"'nonce-{{nonce}}'"` placeholder on `style-src` policy in development.
Resolves discussion #454.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

Not sure how to run tests for development mode.

### CODE REVIEW

**Comment by dargmuesli** [comment]
@vejja @GalacticHypernova would you be so kind to review? :pray:

**Comment by dargmuesli** [comment]
I've tested this change in my projects and it works fine. Without this change having a nonce in `style-src` results in
image
With this change there is no such error in development any more :partying_face:

**Comment by GalacticHypernova** [comment]
Seems good to me at a first glance, will do some local testing soon

**Comment by dargmuesli** [comment]
@Baroshem @vejja anything I can help with to get this merged? :heart:

**Comment by Baroshem** [comment]
Aaa hey Jonas, I completely missed due to other things. 

For me it looks fine. @vejja what are your thoughts? :)

**Comment by Baroshem** [comment]
Released in 2.0.0 :)

**Pull request merged**
