### PR TITLE
fix(ssg): generate meta tag without html,head,body tags

### PR DESCRIPTION
**Pull request by mtdvlpr**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

By default `cheerio.load` will introduce `<html>`, `<head>` and `<body>` elements if they are not present in the argument. This causes the following code to add duplicate `<html>`, `<head>` and `<body>` elements inside the already existing `<head>`.

See [their docs](https://cheerio.js.org/docs/basics/loading#load).

This PR fixes this by disabling the default behaviour of the load function.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by vejja** [comment]
Thanks @mtdvlpr for catching the bug and fixing !

**Comment by Baroshem** [comment]
Hey @mtdvlpr 

Thank you so much for catching it and preparing a fix pull request! I will merge it on monday and release a patch version :)

**Comment by Baroshem** [comment]
Thanks @mtdvlpr 

Released in 1.2.1 patch version :)

**Comment by Baroshem** [comment]
@mtdvlpr 

New patch version is available in NPM image

Regarding github release, you are correct. I dont usually do releases for patch versions unless there is a lot of bugs fixed. I reserve GitHub release for minor and major releases :)

**Pull request merged**
