### PR TITLE
feat: add enabled config option

### LINKED ISSUE #70: Can we access the default middleware options for headers to prevent errors in dev mode?
Is there a way to access the default headers used by the module? It is a pain to deal with SSL and other errors during dev mode, and it would be great if we could do something like this:

```
// nuxt.config.ts
security: {
  headers: process.dev ? false : defaultHeaders
}
````

### PR DESCRIPTION
**Pull request by Baroshem**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
Closes #70 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by ymansurozer** [comment]
This looks just great! :) @Baroshem

**Comment by Baroshem** [comment]
Awesome @ymansurozer I will then release it as a part of the next project release (preferably end of this week) 😃

**Comment by ymansurozer** [comment]
@Baroshem do you think you can merge this soon? I would love to start using it for my current project.

**Comment by Baroshem** [comment]
Hey, yes, I will try to release a new version tomorrow as there are few features that require my review before merging and releasing :)

**Comment by Baroshem** [comment]
@ymansurozer 

The feature should be available with the newest version (0.10.0) :)

**Pull request merged**
