### PR TITLE
update(doc): recommend useScript for Nuxt 3.11+

### PR DESCRIPTION
**Pull request by vejja**
Modify notes to recommend `useScript`

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

For Nuxt version 3.11 and above, `useScript` allows to insert any external script in a CSP-compatible way.
Update documentation to recommend `useScript`.

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by vejja** [comment]
@Baroshem I'm thinking maybe I should remove all references to `useHead` and push them back at the end of the document, because now the text is very long and it doesn't help with clarity
What's your opinion ?

**Comment by Baroshem** [comment]
Hey @vejja . 

Thanks for this note! It is much cleaner now!

Regardinng getting rid of useHead. Yes please do so! Lets keep one format that we want to recommend users to follow. UseScript should be recommended approach from now on :)

**Comment by vejja** [comment]
@Baroshem please don't merge this yet, I'm reverting to draft
Reason is, @harlan-zw released the stable version of `useScript` yesterday, so I want to update usage notes first

**Comment by harlan-zw** [comment]
Hi @vejja, I've sent you access to Nuxt Scripts, maybe it will help with this PR.

**Comment by vejja** [comment]
> Hi @vejja, I've sent you access to Nuxt Scripts, maybe it will help with this PR.

Indeed, thanks !

**Comment by Baroshem** [comment]
Hey @vejja 

Should this pull request be still draft? Not sure what is the actual state of it :) 

Also, could you contact me in any channels like Discord, X, Linkedin? I would love to get more contact with you so that we could discuss certain things more easily :)

**Comment by vejja** [comment]
> Hey @vejja
> 
> Should this pull request be still draft? Not sure what is the actual state of it :)
> 
> Also, could you contact me in any channels like Discord, X, Linkedin? I would love to get more contact with you so that we could discuss certain things more easily :)

Yes it is still draft, I need to update for idle status removal 
Will contact you separately

**Comment by vejja** [comment]
@Baroshem 
The docs are now updated for `useScript` v1.9.4 (released yesterday) which is even simpler because we can skip using `trigger` 🚀
But I'm still keeping this as draft because Nuxt 3.11.1 still pins `unhead` to v1.8.20 (which has the old syntax). I will mark it as ready in the next release of Nuxt.

**Comment by vejja** [comment]
@Baroshem this is good to go !
Nuxt 3.11.2 now includes `unhead` 1.9.4 with its wonderful `useScript` magic 🚀

Many many thanks to @harlan-zw for ensuring `useScript` is CSP-compatible, mostly
- replacing inline event handlers with addEventListener bindings
- ensuring `strict-dynamic` works even with SSG by making it client-first by default
🙏🏻

**Review by Baroshem — APPROVED** [review]

**Comment by Baroshem** [comment]
Awesome @vejja 💚

Thanks for this great write up! I will merge it and publish quite soon!

**Review by Baroshem — APPROVED** [review]

**Pull request merged**
